openapi: 3.0.1
info:
  title: Verbünde
  description: >

    # Beschreibung
    
    Informationen bezüglich der Verbünde(Associates) sollen von OSP gelesen und nach OSP geschrieben werden.
    
    ## Backendsystem
    
    OneSystem Plus (OSP)

    # Rahmenbedingungen
    
    Welche Rahmenbedingungen sind zu beachten, damit der Service genutzt werden kann, insbesondere
      - Rechte: Der aufrufende User muss in ESBConfig die Berechtigung zum Aufruf von Service 'DynsBA'/Domäne OSP besitzen. 
        Zur Abfrage von Daten zu Mitarbeitern (Organkennzeichen gesetzt) benötigt der zugeordnete SUSer das Privileg 'MITARBEITER' und 'VERBUND-Anlegen'. 
        Falls das Zugriffsschutz-Kennzeichen einer gesuchten Personen gesetzt ist
        (ZUGRIFFSSCHUTZ_KZ = 'J' ), benötigt der Anwender das Privileg 'ZUGRIFF-PERS'.
      - Verfügbarkeitszeiten: Wann ist der Service verfügbar?
      - Offene Detailpunkte:
      - Rechte: Im Zielzustand sollte mit der Vergabe des Rechts zur Nutzung des Service auch alle darunterliegenden Rechte, die erforderlich sind, angelegt werden (Service-Gedanke)
      - Serviceparameter: weitergehende Regelungen wie Quotas etc. sind nicht Teil der Swagger-Dokumentation, sondern Parameter im API-Gateway, werden dort gepflegt und publiziert

    # Domäne/Subdomäne
      - Der Service ist der fachlichen Domäne 'PERSON' zugeordnet.
      - Die Informationen werden aus den OSP Prozessgruppen 'VERBUND' bezogen.

    # IT-System(-nummer)
      - Welchem IT-System ist der Service zugeordnet.
      - Der Service erbt von dem IT-System einige wesentliche Eigenschaften, insbesondere die Ownerschaften und das Schutz-Niveau, das der Service bietet.
      - Bei Composite Services über mehrere Systeme gibt i.d.R. ein System, das führend ist (Einstiegspunkt). Der Service wird diesem System zugeordnet.
      
    # Offene Detailpunkte
      - Welche Eigenschaften erbt der Service von dem System?
      - Werden diese Eigenschaften beim Service im API-Verzeichnis mit publiziert (Komfort) und/oder das IT-System verlinkt.
      - Wird die Systemnummer publiziert?
      - Sollte es eine eigene Domäne 'Verbünde' geben ?

    # Schutzniveau
    
    Schutz-Niveau des IT-Systems oder geringer
    
    # Release-Notes
    
      - 2020-09-09: v0.0.1  Erster Entwurf der Operationen und Modellen.
      - 2020-09-17: v0.0.2  Anpassungen nach dem ersten technischen Review.

    # Status
    
        Version v0.0.2  Anpassungen nach dem ersten technischen Review.
  version: v0.0.2
  termsOfService: /agb
  contact:
    name: Nicholas Trawniczek
    url: 'http://api.lbbw.de'
    email: Nicholas.Trawniczek@lbbw.de
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-keywords: >-
    Verbund, Verbunde, Verbünde, Verbundmerkmale, Person, Personen, KYC, Konto, Konten
  x-logo:
    altText: OSPlus logo
    url: 'assets/img/osplus.png'
servers:
  - url: 'http://api.bp.entw.bank.lbbw.sko.de/customer/associate-service/'
    description: API-Verzeichnis
  - url: 'http://esb.bp.entw.bank.lbbw.sko.de/customer/associate-service/'
    description: ESB-Service Integrationsumgebung
externalDocs:
  description: Diese Dokumentation basiert auf der Open Api Specification V3.
  url: 'https://github.com/OAI/OpenAPI-Specification'
tags:
  - name: associate_models
    x-displayName: Verbund
    description: |
        Datenmodell eines Verbunds
        <SchemaDefinition schemaRef="#/components/schemas/Associate" showReadOnly={true} showWriteOnly={true} />
        
        Datenmodell zum Erstellen eines Verbunds
        <SchemaDefinition schemaRef="#/components/schemas/PostAssociatesRequest" showReadOnly={true} showWriteOnly={true} />
        
        Datenmodell zum Ändern eines Verbunds
        <SchemaDefinition schemaRef="#/components/schemas/PutAssociatesRequest" showReadOnly={true} showWriteOnly={true} />            
  - name: health_model
    x-displayName: Health
    description: |
       <SchemaDefinition schemaRef="#/components/schemas/HealthOkResponse" showReadOnly={true} showWriteOnly={true} />
       <SchemaDefinition schemaRef="#/components/schemas/HealthErrorResponse" showReadOnly={true} showWriteOnly={true} />
x-tagGroups:
  - name: Verbünde
    tags:
      - associates
  - name: Health-Check
    tags:
      - health
  - name: Datenmodelle
    tags:
      - associate_models
      - health_model
security:
  - EsbAuthorization: []
    appId: []

paths:
  /associates/customers/{customer_id}:
    get:
      operationId: getAssociatesByCustomerId
      tags: [associates]
      summary: Abrufen aller Verbünde eines Kunden.
      description: Alle Verbünde, in der eine Person eine Rolle hat, sind auszugeben.
      parameters:
        - name: customer_id
          in: path
          description: Personennummer.
          required: true
          schema:
            $ref: '#/components/schemas/CustomerId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAssociatesByCustIdResponse'
        '204':
          description: Customer not found
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /associates/{associate_id}:
    get:
      operationId: getAssociateById
      tags: [associates]
      summary: Abrufen aller Personen eines Verbunds.
      description: Alle Personen, die zu einem Verbund gehören, sind auszugeben.
      parameters:
        - name: associate_id
          in: path
          description: Verbund-ID Base64 encodiertes Timestamp.
          required: true
          schema:
            $ref: '#/components/schemas/Associate_id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAssociateResponse'
        '204':
          description: Associate not found
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      operationId: putAssociates
      tags: [associates]
      summary: Eine weitere Person soll in einen bestehenden Verbund aufgenommen werden.
      description: >-
        Eine Person ist mit ihrer Rolle dem Verbund zuzuordnen. DynS-Funktion: PERSONEN_ZU_VERBUND_HINZUF
      parameters:
        - name: associate_id
          in: path
          description: Verbund-ID Base64 encodiertes Timestamp.
          required: true
          schema:
            $ref: '#/components/schemas/Associate_id'
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/PutAssociatesRequest'
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/PutAssociatesResponse'
        '400':
          description: Bad Request
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /associates:
    post:
      operationId: postAssociates
      tags: [associates]
      summary: Ein neuer Verbund mit Personen wird angelegt, die neue Verbund-ID wird zurück gemeldet.
      description: >-
        Alle Personen, die zu einem Verbund gehören, sind mit ihrer Rolle dem Verbund zuzuordnen. 
        DynS-Funktion: VERBUND_PERSONEN_ANLEGEN
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/PostAssociatesRequest'
      responses:
        '201':
          description: OK
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/PostAssociatesResponse'
        '400':
          description: Bad Request
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /health:
    get:
      security: []
      tags: [health]
      summary: Allgemeiner Healthcheck.
      description: >-
        Dieser muss ohne Autorisierung aufrufbar sein. Die Minimalanforderung ist ein {status: 'UP'} 
        wenn der Service gerufen werden kann.
      operationId: getHealthStatus
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthOkResponse"
              example:
                status: "UP"
        '503':
          description: Error - Meldung nur möglich, wenn Prüfung ausserhalb des Service erfolgt.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthErrorResponse'
              example:
                status: "OUT_OF_SERVICE"
components:
  schemas:
# Verbünde zu Person lesen:
    GetAssociatesByCustIdResponse:
      type: object
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/Associates'
        message_text:
          $ref: '#/components/schemas/Message_text'
        links:
          type: object
          properties:
            self: 
              type: string
              example: 'http://api.bp.entw.bank.lbbw.sko.de/customer/associate-service/associates/customers/630188'
    Associates:
      description: Liste von Verbünden.
      required:
      - associates
      properties:
        associates:
          type: array
          minItems: 0
          maxItems: 50
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Associate'
          #example:
          #  - customer_id: 630188
          #    role: GBR
          #  - customer_id: 17
          #    role: EIGENTÜMER
# Personen zu Verbund lesen
    GetAssociateResponse:
      type: object
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/Associate'
        message_text:
          $ref: '#/components/schemas/Message_text'
        links:
          type: object
          properties:
            self: 
              type: string
              example: 'http://api.bp.entw.bank.lbbw.sko.de/customer/associate-service/associates/MTkyNi0wNC0xNC0xMi4yMy40MS4xMDc2MTc'
# Verbund anlegen:   
    PostAssociatesRequest:
      type: object
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/Associate'
    PostAssociatesResponse:
      type: object
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/Associate'
    Associate:
      type: object
      description: Verbund von Kunden.
      required:
      - type
      - attributes
      properties:
        id:
          $ref: '#/components/schemas/Associate_id'
        type:
          type: string
          description: Objekt Type
          example: associates
          enum:
            - associates
        attributes:
          type: object
          required:
          - customers
          properties:
            customers:
              $ref: '#/components/schemas/Customers' 
            associate_type:
              type: string
              example: 'TYPE_1'
              description: >- 
               Verbundart. Zusammenfassung mehrerer Rollen. Eine Rolle kann nur einer Rollenart zugeordnet werden. 
               Die Verbundart wird über den Inputparameter ROLLENART festgelegt.
            note:
              type: string
              example: 'note_text'
              description: >- 
               TEXT_PARTNER. Lt. fachlicher Beschreibung des DynS-Prozesses kann ein Merkmal zu einer Verbundrolle über den optionalen 
               Parameter TEXT_PARTNER erfasst werden.

# Verbund erweitern:   
    PutAssociatesRequest:
      type: object
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/Associate'
    PutAssociatesResponse:
      type: object
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/Associate'
        message_text:
          $ref: '#/components/schemas/Message_text'
# Hilfs-Modelle:
    Associate_id:
      type: string
      description: >-
        Verbund_ID. Eindeutige Identifizierung eines Verbundes. ID-Timestamp des Verbundes in Base64.
      maxLength: 26
      example: MTkyNi0wNC0xNC0xMi4yMy40MS4xMDc2MTc
    Customer:
      description: Person/Kunde aus der Sicht eines Verbundes.
      required:
      - customer_id
      - role
      properties:
        customer_id:
          $ref: '#/components/schemas/CustomerId'
        role:
          type: string
          maxLength: 12
          description: >- 
            ROLLE. Personen Rolleninformationen. Eintrag in der Partnertabelle kennzeichnet 
              a) Rolle der Person i.S. DBGK oder 
              b) Existenz bestimmter Informations-Objekte (Anschrift, Statistikdaten etc.) in der Personen-DB.
    Customers:
      description: Liste von Kunden die einen Verbund darstellen.
      required:
      - customers
      properties:
        customers:
          type: array
          minItems: 0
          maxItems: 50
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Customer'
          example:
            - customer_id: 630188
              role: GBR
            - customer_id: 17
              role: EIGENTÜMER
    CustomerId:
      type: string
      description: >-
        KUSA. Eindeutiger Schlüssel des Kunden.
      maxLength: 10
      pattern: '\d{1,10}'
      example: '630188'
    Message_text:
      type: string
      description: Meldungstext.
      example: 'Noch weitere Daten vorhanden.'
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/JsonApiError'
    JsonApiError:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        code:
          type: string
        title:
          type: string
        detail:
          type: string
    # HealthCheck analog zu SpringBoot
    HealthOkResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - UP
        components:
          type: object
    HealthErrorResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - OUT_OF_SERVICE
        components:
          type: object
  securitySchemes:
    EsbAuthorization:
      type: http
      scheme: basic
    appId:
      type: apiKey
      in: header
      name: x-app-id
      description: Applikationskürzel zum FIA-User (wird zur Zuordnung des Client benutzt)
