openapi: 3.0.3

info:

  title: Ländercode-Service

  x-keywords: Ländercode, Länderschlüssel

  description: |

    # Beschreibung

    Der Service liefert bei Eingabe eines ISO-Ländercodes den entsprechenden OS-Plus-Ländercode innerhalb eines Countrycode-Objekts zurück.

    

    # Domäne/Subdomäne

    Der Service gehört zur API-Domäne 'Hilfsmittel' und ist unter /countrycodes erreichbar.

    

    # Schutzniveau

    Da die Daten öffentlich bei der Bundesbank verfügbar sind, ist das Schutzniveau gering.

    

    # Release-Notes

    - 2020-12-17: v1.0.2  Überarbeitung gemäß Telko

    - 2020-12-15: v1.0.1  Titel und Service URL entsprechend Checkliste.

    - 2021-02-18: v1.0.2  APIM-658 anstatt des Bundesbank-Ländercodes soll der Ländercode aus OS-Plus zurückgegeben werden 

    - 2021-03-02: v1.0.3  APIM-658 es ist nur noch die Richtung ISO-Ländercode -> OS-Plus-Ländercode möglich   

  termsOfService: '/agb'

  contact:

    name: API-Management Support (Karin Seidle)

    url: http://api.lbbw.de

    email: karin.seidle@lbbw.de

  version: 1.0.6

  x-logo:

    altText: LBBW Logo

    url: 'assets/img/lbbw-logo-blue.svg'

  license:

    name: Apache 2.0

    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

 

externalDocs:

  description: Diese Dokumentation basiert auf der Open Api Specification V3.

  url: https://github.com/OAI/OpenAPI-Specification

servers:

- url: 'https://api.bp.prod.bank.lbbw.sko.de/utility'

  description: URL des Servers

 

 

tags:

- name: getCountryCodes

  description: Abfrage nach einem Countrycode

- name: getCountryCodesById

  description: Abruf eines Countrycode

- name: health

  description: Healthcheck, prüft ob der Service läuft

- name: countrycode_model

  description: |

    <SchemaDefinition schemaRef="#/components/schemas/Countrycodes" showReadOnly={true} showWriteOnly={true} />

  x-displayName: Ländercode

- name: health_model

  description: |

    <SchemaDefinition schemaRef="#/components/schemas/HealthCheckOkResponse"  showReadOnly={true} showWriteOnly={true} />

    <SchemaDefinition schemaRef="#/components/schemas/HealthCheckErrorResponse" showReadOnly={true} showWriteOnly={true} />

  x-displayName: Health-Check

 

x-tagGroups:

- name: Ländercodes

  tags:

    - countrycodes

- name: HealthCheck

  tags:

    - health

- name: Datenmodelle

  tags:

    - countrycode_model

    - health_model

paths:

  '/countrycodes':

    get:

      tags: [countrycodes]

      summary: Filtert die Countrycodes nach Iso- oder OS-Plus-Code

      operationId: query

      parameters:

        - in: query

          name: isocode

          schema:

            type: string

          description: IsoCode

      responses:

        '200':

          description: OK

          content:

            application/hal+json:

              schema:

                type: array

                items: 

                  $ref: '#/components/schemas/Countrycodes'

        '400':

          description: bad request

          content:

            application/json:

              schema:

                $ref: '#/components/schemas/BadRequestError'

  '/countrycodes/{isocode}':

    get:

      tags: [countrycodes]

      summary: Gibt ein passendes Countrycodes-Objekt zurück

      operationId: id

      parameters:

        - name: isocode

          in: path

          required: true

          schema:

            type: string

      responses:

        '200':

          description: OK

          content:

            application/hal+json:

              schema:

                $ref: '#/components/schemas/Countrycodes'

        '400':

          description: bad request

          content:

            application/json:

              schema:

                $ref: '#/components/schemas/BadRequestError'

        '404':

         description: Objekt konnte nicht gefunden werden

          content:

            application/json:

              schema:

                $ref: '#/components/schemas/NotFoundError'

  '/health':

    get:

      tags: [health]

      summary: Endpunkt zur Überprüfung, ob die Applikation auf dem Server läuft

      operationId: healthCheck

      responses:

        '200':

          description: OK

          content:

            'application/json':

              schema:

                $ref: '#/components/schemas/HealthCheckOkResponse'

        '503':

          description: Error - Meldung nur möglich, wenn Prüfung ausserhalb des Service erfolgt.

          content:

            'application/json':

              schema:

                $ref: '#/components/schemas/HealthCheckErrorResponse'

components:

  schemas:        

    Countrycodes:

      type: object

      properties:

        _links:

          type: object

          properties:

            self:

              type: object

              properties:

                href:

                  type: string

                  example: 'https://api.bp.prod.bank.lbbw.sko.de/utility/countrycodes/001'

        isocode:

          type: string

          example: 'FR'

          description: ISO-Alpha2-Code

        ospluscode:

          type: string

          example: '001'

          description: OS-Plus Länderschlüssel

    NotFoundError:

      type: object

      properties:

        status:

          type: string

          example: not found

    BadRequestError:

      type: object

      properties:

        status:

          type: string

          example: bad request

    HealthCheckOkResponse:

      type: object

      required:

        - status

      properties:

        status:

          type: string

          enum:

            - UP

            - UNKNOWN

          example: 'UP'

    HealthCheckErrorResponse:

      type: object

      required:

        - status

      properties:

        status:

          type: string

          enum:

            - DOWN

            - OUT_OF_SERVICE

          example: 'DOWN'
