openapi: 3.0.1
info:
  title: Associate-Service
  description: >

    # Beschreibung
    
    Informationen bezüglich der Verbunde(Associates) sollen von OSP gelesen und nach OSP geschrieben werden.
    
    ## Backendsystem
    
    OneSystem Plus (OSP)

    # Rahmenbedingungen
    
    Welche Rahmenbedingungen sind zu beachten, damit der Service genutzt werden kann, insbesondere
      - Rechte: Der aufrufende User muss in ESBConfig die Berechtigung zum Aufruf von Service 'DynsBA'/Domäne OSP besitzen. 
        Zur Abfrage von Daten zu Mitarbeitern (Organkennzeichen gesetzt) benötigt der zugeordnete SUSer das Privileg 'MITARBEITER' und 'VERBUND-Anlegen'. 
        Falls das Zugriffsschutz-Kennzeichen einer gesuchten Personen gesetzt ist
        (ZUGRIFFSSCHUTZ_KZ = 'J' ), benötigt der Anwender das Privileg 'ZUGRIFF-PERS'.
      - Verfügbarkeitszeiten: Wann ist der Service verfügbar?
      - Offene Detailpunkte:
      - Rechte: Im Zielzustand sollte mit der Vergabe des Rechts zur Nutzung des Service auch alle darunterliegenden Rechte, die erforderlich sind, angelegt werden (Service-Gedanke)
      - Serviceparameter: weitergehende Regelungen wie Quotas etc. sind nicht Teil der Swagger-Dokumentation, sondern Parameter im API-Gateway, werden dort gepflegt und publiziert

    # Domäne/Subdomäne
      - Der Service ist der fachlichen Domäne 'Customer' zugeordnet.
      - Die Informationen werden aus den OSP Prozessgruppen 'PERSON' und 'VERBUND' bezogen.

    # IT-System(-nummer)
      - Welchem IT-System ist der Service zugeordnet.
      - Der Service erbt von dem IT-System einige wesentliche Eigenschaften, insbesondere die Ownerschaften und das Schutz-Niveau, das der Service bietet.
      - Bei Composite Services über mehrere Systeme gibt i.d.R. ein System, das führend ist (Einstiegspunkt). Der Service wird diesem System zugeordnet.
      
    # Offene Detailpunkte
      - Welche Eigenschaften erbt der Service von dem System?
      - Werden diese Eigenschaften beim Service im API-Verzeichnis mit publiziert (Komfort) und/oder das IT-System verlinkt.
      - Wird die Systemnummer publiziert?

    # Schutzniveau
    
    Schutz-Niveau des IT-Systems oder geringer
    
    # Release-Notes
    
      - 2020-09-09: v0.0.1  Erster Entwurf der Operationen und Modellen.

    # Status
    
        Version v0.0.1  Erster Entwurf der Operationen und Modellen.
  version: v0.0.1
  termsOfService: /agb
  contact:
    name: Nicholas Trawniczek
    url: 'http://api.lbbw.de'
    email: Nicholas.Trawniczek@lbbw.de
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-keywords: >-
    Verbund, Verbünde, Verbundmerkmale, Person, Personen, KYC
  x-logo:
    altText: LBBW logo
    url: 'https://www.lbbw.de/res/images/logos/lbbw-logo-darkblue_131586_m.svg'
servers:
  - url: 'http://api.bp.entw.bank.lbbw.sko.de/customer/associate-service/'
    description: API-Verzeichnis
  - url: 'http://esb.bp.entw.bank.lbbw.sko.de/customer/associate-service/'
    description: ESB-Service Integrationsumgebung
externalDocs:
  description: Diese Dokumentation basiert auf der Open Api Specification V3.
  url: 'https://github.com/OAI/OpenAPI-Specification'
tags:
  - name: post_associate_models
    x-displayName: Create Associates
    description: |
        Datenmodell für einen Request
        <SchemaDefinition schemaRef="#/components/schemas/PostAssociatesRequest" showReadOnly={true} showWriteOnly={true} />
        Datenmodell für einen Response 
        <SchemaDefinition schemaRef="#/components/schemas/PostAssociatesResponse" showReadOnly={true} showWriteOnly={true} />
  - name: put_associate_models
    x-displayName: Extend Associates
    description: |
        Datenmodell für einen Request
        <SchemaDefinition schemaRef="#/components/schemas/PutAssociatesRequest" showReadOnly={true} showWriteOnly={true} />
        Datenmodell für einen Response 
        <SchemaDefinition schemaRef="#/components/schemas/PutAssociatesResponse" showReadOnly={true} showWriteOnly={true} />
  - name: health_model
    x-displayName: Health
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/HealthOkResponse" showReadOnly={true} showWriteOnly={true} />
       <SchemaDefinition schemaRef="#/components/schemas/HealthErrorResponse" showReadOnly={true} showWriteOnly={true} />
x-tagGroups:
  - name: Associate
    tags:
      - associates
  - name: Healthcheck
    tags:
      - health
  - name: Models
    tags:
      - post_associate_models
      - put_associate_models
      - health_model
security:
  - EsbAuthorization: []
    appId: []

paths:
  /associates:
    post:
      operationId: postAssociates
      tags: [associates]
      summary: Ein neuer Verbund mit Personen wird angelegt, die neue Verbund-ID wird zurück gemeldet.
      description: >-
        Alle Personen, die zu einem Verbund gehören, sind mit ihrer Rolle dem Verbund zuzuordnen. 
        DynS-Funktion: VERBUND_PERSONEN_ANLEGEN
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/PostAssociatesRequest'
      responses:
        '201':
          description: OK
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/PostAssociatesResponse'
        '400':
          description: Bad Request
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /extendassociates:
    put:
      operationId: putAssociates
      tags: [associates]
      summary: Eine weitere Person soll in einen bestehenden Verbund aufgenommen werden.
      description: >-
        Eine Person ist mit ihrer Rolle dem Verbund zuzuordnen. DynS-Funktion: PERSONEN_ZU_VERBUND_HINZUF
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/PutAssociatesRequest'
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/PutAssociatesResponse'
        '400':
          description: Bad Request
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /health:
    get:
      security: []
      tags: [health]
      summary: Allgemeiner Healthcheck.
      description: >-
        Dieser muss ohne Autorisierung aufrufbar sein. Die Minimalanforderung ist ein {status: 'UP'} 
        wenn der Service gerufen werden kann.
      operationId: getHealthStatus
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthOkResponse"
              example:
                status: "UP"
        '503':
          description: Error - Meldung nur möglich, wenn Prüfung ausserhalb des Service erfolgt.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthErrorResponse'
              example:
                status: "OUT_OF_SERVICE"
components:
  schemas:
# Verbund anlegen:   
    PostAssociatesRequest:
      type: object
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/Associate'
    PostAssociatesResponse:
      type: object
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/Associate'
    Associate:
      type: object
      description: Verbund anlegen oder erweitern.
      required:
      - type
      - attributes
      properties:
        id:
          type: string
          example: MDAwMS0wMS0wMS0wMC4wMC4wMC4wMDAwMDA
          description: >-
                Verbund_ID. Eindeutiger Schlüssel, Base64 encodierter ID-Timestamp des Verbundes.
        type:
          type: string
          description: Objekt Type
          example: associates
          enum:
            - associates
        attributes:
          type: object
          required:
          - associates
          - roles
          properties:
            associates:
              type: array
              minItems: 0
              maxItems: 50
              uniqueItems: true
              items:
                $ref: '#/components/schemas/CustomerId'
              example: ['17', '630188']
              description: >- 
                Personen_NR die zu einem Verbund angelegt werden sollen.
            roles:
              type: array
              minItems: 0
              maxItems: 50
              uniqueItems: true
              items:
                $ref: '#/components/schemas/Role'
              example: ['ROLLE_1', 'ROLLE_2', 'ROLLE_3']
              description: >- 
                Eintrag in der Partnertabelle kennzeichnet 
                  a) Rolle der Person i.S. DBGK oder 
                  b) Existenz bestimmter Informations-Objekte (Anschrift, Statistikdaten etc.) in der Personen-DB.
            role_type:
              type: string
              example: 'ROLLEN_TYP_1'
              description: >- 
               Verbundart. Zusammenfassung mehrerer Rollen. Eine Rolle kann nur einer Rollenart zugeordnet werden. 
               Die Verbundart wird über den Inputparameter ROLLENART festgelegt.
            mark:
              type: string
              example: 'Merkmal_1'
              description: >- 
               Lt. fachlicher Beschreibung des DynS-Prozesses kann ein Merkmal zu einer Verbundrolle über den optionalen 
               Parameter TEXT_PARTNER erfasst werden.
            messageText:
              type: string
              description: >- 
                Meldungstext aus dem DynS-Prozess.
              example: 'MGK16340N010 - Der Prozess wurde erfolgreich ausgefuehrt.'
    # Verbund erweitern:   
    PutAssociatesRequest:
      type: object
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/Associate'
    PutAssociatesResponse:
      type: object
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/Associate'
    CustomerId:
      type: string
      description: >-
        KUSA. Eindeutiger Schlüssel des Kunden.
      maxLength: 10
      pattern: '\d{1,10}'
      example: '630188'
    Role:
      description: Personen Rolleninformationen
      required: 
      - role
      properties:
        role: 
          description: Rolle der Person.
          type: string
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/JsonApiError'
    JsonApiError:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        code:
          type: string
        title:
          type: string
        detail:
          type: string
    # HealthCheck analog zu SpringBoot
    HealthOkResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - UP
        components:
          type: object
    HealthErrorResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - OUT_OF_SERVICE
        components:
          type: object
  securitySchemes:
    EsbAuthorization:
      type: http
      scheme: basic
    appId:
      type: apiKey
      in: header
      name: x-app-id
      description: Applikationskürzel zum FIA-User (wird zur Zuordnung des Client benutzt)
